export enum AccessErrorType {
  // username/password invalid
  InvalidCredentials = 100,

  // Token invalid. Eg: trying to use the token not generated by system.
  InvalidToken = 101,

  // Token expired.
  ExpiredToken = 102,

  // Missing token
  MissingToken = 103,

  MissingInfo = 104,

  ResetTokenInvalid = 105,

  ResetTokenUsed = 106,

  ResetTokenExpired = 107,

  NotAuthorised = 108,

  NotFound = 404,
}
